### ISSUE TITLE
Can't access rTorrent running in another Docker container

### ISSUE THREAD

**Issue by flatline-studios** [Flood-UI/flood#820]
Type: Question

Pulling my hair out here a little bit...

I have:

```
version: '3'
services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1002
      - PGID=998
    volumes:
      - /home/dockerr/configs/rutorrent:/config
      - /data/downloads/torrents/rutorrent:/downloads
    ports:
      - 8888:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

  flood:
    image: flood
    container_name: flood
    environment:
      - FLOOD_SECRET=6b66e412b12e14fcc7a092
    volumes:
      - /home/dockerr/configs/flood:/data
    ports:
      - 3000:3000
    restart: unless-stopped
```

When I load up these containers, and connect to `localhost:3000`, I get the login screen, and then when I reach: http://prntscr.com/oruak0 - This screen, as far as I'm aware, it *should* work, but doesn't...

Anyone have any idea where I'm going wrong? Where I can check for issues, etc?
